/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Accounting } from "./Accounting";
import { AccountingCountArgs } from "./AccountingCountArgs";
import { AccountingFindManyArgs } from "./AccountingFindManyArgs";
import { AccountingFindUniqueArgs } from "./AccountingFindUniqueArgs";
import { DeleteAccountingArgs } from "./DeleteAccountingArgs";
import { AccountingService } from "../accounting.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Accounting)
export class AccountingResolverBase {
  constructor(
    protected readonly service: AccountingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Accounting",
    action: "read",
    possession: "any",
  })
  async _accountingsMeta(
    @graphql.Args() args: AccountingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Accounting])
  @nestAccessControl.UseRoles({
    resource: "Accounting",
    action: "read",
    possession: "any",
  })
  async accountings(
    @graphql.Args() args: AccountingFindManyArgs
  ): Promise<Accounting[]> {
    return this.service.accountings(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Accounting, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Accounting",
    action: "read",
    possession: "own",
  })
  async accounting(
    @graphql.Args() args: AccountingFindUniqueArgs
  ): Promise<Accounting | null> {
    const result = await this.service.accounting(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Accounting)
  @nestAccessControl.UseRoles({
    resource: "Accounting",
    action: "delete",
    possession: "any",
  })
  async deleteAccounting(
    @graphql.Args() args: DeleteAccountingArgs
  ): Promise<Accounting | null> {
    try {
      return await this.service.deleteAccounting(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
