/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Accounting as PrismaAccounting } from "@prisma/client";

export class AccountingServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AccountingCountArgs, "select">
  ): Promise<number> {
    return this.prisma.accounting.count(args);
  }

  async accountings(
    args: Prisma.AccountingFindManyArgs
  ): Promise<PrismaAccounting[]> {
    return this.prisma.accounting.findMany(args);
  }
  async accounting(
    args: Prisma.AccountingFindUniqueArgs
  ): Promise<PrismaAccounting | null> {
    return this.prisma.accounting.findUnique(args);
  }
  async createAccounting(
    args: Prisma.AccountingCreateArgs
  ): Promise<PrismaAccounting> {
    return this.prisma.accounting.create(args);
  }
  async updateAccounting(
    args: Prisma.AccountingUpdateArgs
  ): Promise<PrismaAccounting> {
    return this.prisma.accounting.update(args);
  }
  async deleteAccounting(
    args: Prisma.AccountingDeleteArgs
  ): Promise<PrismaAccounting> {
    return this.prisma.accounting.delete(args);
  }
}
